#!/bin/bash

show_help()
{
    echo "SYNTAX: `basename $0` <FILENAME> <SEARCH_STR> <REPLACE_STR> [IGNORE_COLLISION={1/0}]"
}

if [ $# -ne 3 -a $# -ne 4 ]; then
    echo "fail! -- expect 3 or 4 arguments! ==> $@"
    show_help
    exit 1
fi

FILENAME=$1
SEARCH_STR=$2
REPLACE_STR=$3
IGNORE_COLLISION=$4

find . -name "*" | grep $FILENAME | grep -v "\.git" | xargs -I{} bash -c "refact {} $SEARCH_STR $REPLACE_STR $IGNORE_COLLISION"

echo "done! ==> $@"
